name: Staging deploy
on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Setup AWS -- begin
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::257838883645:role/GitHub
          aws-region: us-east-1
          output-credentials: true

      - name: Install Amazon ECR Docker Credential Helper # Requried to securly log in to AWS ECR. `docker login` with `aws ecr get-login-password` is insecure.
        run: |
          sudo apt-get update
          sudo apt-get install -y amazon-ecr-credential-helper

      - name: Configure Docker to use ECR Credential Helper
        run: |
          mkdir -p ~/.docker
          echo '{"credsStore": "ecr-login"}' > ~/.docker/config.json
      # Setup AWS -- end

      - name: Build and Push Docker image - server
        env:
          IMAGE_NAME: 257838883645.dkr.ecr.us-east-1.amazonaws.com/pnpm-mono/server:${{ github.sha }}
        run: |
          docker build . --target server --tag $IMAGE_NAME
          docker push $IMAGE_NAME
